module.exports = [
['Generic reactions', 1, 0, 1, 0, '"oh ah oh oh ooooh"'],
['Generic reactions', 1, 0, 1, 1, '"gaah (whispering) eugh!"'],
['Generic reactions', 1, 0, 1, 5, '"you like? Is all natural!"'],
['Generic reactions', 1, 1, 0, 1, '"doh, really?"', 'questioning,confused'],
['Generic reactions', 1, 1, 0, 2, '"eeeeeehhhh"'],
['Generic reactions', 1, 1, 0, 3, 'wookie yawn', 'starwars,movies'],
['Generic reactions', 1, 1, 0, 4, '"ooohmm.. Yay! (unexcited)"', 'unexcited'],
['Generic reactions', 1, 1, 0, 5, '"ka-rumph"', 'unexcited'],
['Generic reactions', 1, 2, 0, 0, 'yawn "besties?"', 'friendly,sleepy'],
['Generic reactions', 1, 2, 0, 1, 'yawn "warm fuzzies"', 'friendly,sleepy'],
['Generic reactions', 1, 2, 0, 2, '"oooohhh, kah favorite!"', 'content,loving'],
['Generic reactions', 1, 2, 0, 3, '"ohohohoh… smoops"', 'content,loving'],
['Generic reactions', 1, 2, 0, 5, '"oooh, is this.. For ever??"', 'content,loving,needy'],
['Generic reactions', 1, 2, 0, 6, '"mmm… s s s s"'],
['Generic reactions', 1, 2, 0, 7, '"do do, de de dey da do, da do"', 'sleepy,singing'],
['Generic reactions', 1, 2, 1, 0, '"aaah, kah on cloud nine, no, cloud ten"', 'sleepy,content'],
['Generic reactions', 1, 2, 1, 1, 'purr "hmm. Kah dreaming?"', 'sleepy,content,purr'],
['Generic reactions', 1, 2, 1, 2, '"I love it!"', 'praise,sleepy'],
['Generic reactions', 1, 2, 1, 4, '"aaah" fart"', 'sigh,fart'],
['Generic reactions', 1, 2, 1, 5, 'sigh', 'sigh'],
['Generic reactions', 1, 3, 0, 1, '"oouuughhh"', 'purr'],
['Generic reactions', 1, 3, 0, 2, '"humming"'],
['Generic reactions', 2, 0, 0, 0, 'frantic laughter'],
['Generic reactions', 2, 0, 0, 1, 'frantic laughter'],
['Generic reactions', 2, 0, 0, 2, 'laughter, squeal'],
['Generic reactions', 2, 0, 1, 0, '"wait, no!" laughter'],
['Generic reactions', 2, 0, 1, 4, 'giggle, fart "oh, excueeze kah!"'],
['Generic reactions', 2, 1, 0, 5, '"he he he he he, hey, wait a minute"'],
['Generic reactions', 2, 2, 0, 1, 'yawn "hmm.. Puppies" yip, giggle'],
['Generic reactions', 2, 2, 1, 0, 'giggle "burger belly"'],
['Generic reactions', 2, 2, 1, 1, 'giggle, sigh'],
['Generic reactions', 4, 1, 0, 4, 'gargle "meh!"'],
['Generic reactions', 4, 1, 0, 6, '"ugh!" mumbles'],
['Generic reactions', 4, 2, 0, 1, 'sleep murmer "cheese fries"'],
['Generic reactions', 4, 3, 0, 8, '"ee-tay, fantastico!"', 'praise'],
['Generic reactions', 4, 3, 0, 9, '"oooh, oo-nye magic"'],
['Generic reactions', 5, 0, 1, 1, '"no, but seriously, kah love this!"', 'praise'],
['Generic reactions', 5, 3, 0, 0, '"hmm. Hug it out"'],
['Conversation parts', 8, 0, 0, 0, '"yaaaas"'],
['Conversation parts', 8, 0, 0, 7, '"what?!!"'],
['Conversation parts', 8, 0, 1, 6, '"woah!"'],
['Conversation parts', 8, 0, 1, 8, 'shocked'],
['Conversation parts', 8, 1, 0, 1, '"huh, this just got weird"'],
['Conversation parts', 8, 1, 0, 2, '"uuuuuuuuuhhhh"'],
['Conversation parts', 8, 1, 0, 3, '"da no likey"'],
['Conversation parts', 8, 1, 0, 4, '"awkward!"'],
['Conversation parts', 8, 3, 0, 0, '"go on"'],
['Conversation parts', 8, 3, 0, 1, '"oh yeah, no totally"'],
['Conversation parts', 8, 3, 0, 2, '"oooh"'],
['Conversation parts', 8, 3, 0, 4, '"daww"'],
['Conversation parts', 8, 3, 0, 5, '"ah ohh!"'],
['Conversation parts', 8, 3, 0, 6, '"hmmm"'],
['Conversation parts', 8, 3, 0, 7, '"huh! Really!?"'],
['Conversation parts', 8, 3, 0, 8, '"oh oh, you!"'],
['Conversation parts', 8, 3, 0, 9, '"mm hmm, totally"'],
['Conversation parts', 8, 3, 0, 10, '"oh, ee-tay, ee-day minds thing alike"'],
['Conversation parts', 8, 3, 0, 11, '"oooooohh, very interesting"'],
['Conversation parts', 8, 3, 0, 12, '"dooo?? Gah boo!"'],
['Conversation parts', 8, 3, 0, 14, '"mm hm, kah no argue with that"'],
['Conversation parts', 8, 3, 0, 15, '"pfth, oo kah tee, did kah tell you" whisphers'],
['Conversation parts', 8, 3, 0, 16, '"what we whisper about?"'],
['Furby Bored', 25, 1, 0, 0, 'yawn'],
['Furby Bored', 25, 1, 0, 1, 'sigh'],
['Furby Bored', 25, 1, 0, 2, '"hmmmmm"'],
['Wakeup actions', 27, 2, 0, 0, '"Buenos días"'],
['Wakeup actions', 27, 2, 0, 1, '"Morning! Rise and shiney, ooh, shiney!"'],
['Wakeup actions', 27, 2, 0, 2, '"Morning! Early furb gets worm, nasty!"'],
['Sleep actions', 28, 0, 0, 2, '"power nap!"'],
['Playing with friend', 30, 1, 1, 0, 'laugh ""no"'],
['Playing with friend', 30, 1, 1, 3, '"uh oh"'],
['Playing with friend', 30, 1, 1, 7, '"honestly, yes"'],
['Playing with friend', 30, 1, 1, 8, '"mmm, maybe"'],
['Playing with friend', 30, 1, 1, 10, '"yaaaaas"'],
['Playing with friend', 30, 1, 1, 11, '"what?"'],
['Playing with friend', 30, 1, 1, 12, '"huh? No, wait, yes, wait, no?"'],
['Playing with friend', 30, 1, 1, 20, '"indeed!"'],
['Playing with friend', 30, 3, 0, 0, 'PUT TO SLEEP'],
['Misc reactions', 32, 0, 0, 0, '"love it!"'],
['Misc reactions', 32, 0, 0, 1, '"so in to this!"'],
['Misc reactions', 32, 0, 1, 0, '"hmm, not so sure"'],
['Misc reactions', 32, 0, 1, 1, '"noo likey!"'],
['Misc reactions', 32, 0, 3, 0, '"caaan dig it"'],
['Misc reactions', 32, 0, 3, 1, '"may-may oo-nye?"'],
['Misc reactions', 32, 0, 4, 0, '"need doctor" coughs up lung'],
['Connected to world app', 34, 0, 0, 2, '"success! Kah has it"'],
['Connected to world app', 34, 0, 0, 3, '"yes! The day is ours" (weird accent)'],
['Connected to world app', 34, 0, 0, 4, '"oooh, oo-nye magic"'],
['Connected to world app', 34, 0, 0, 5, '"dude, dee-doh, yes, very yes"'],
['Connected to world app', 34, 0, 0, 6, '"ooh" silly laugh'],
['Connected to world app', 34, 0, 0, 7, '"neeeeeeehe"'],
['Connected to world app', 34, 0, 0, 8, '"oh ah oh oh oh"'],
['Connected to world app', 34, 1, 0, 0, '"heh, menus, am I right?"'],
['Connected to world app', 34, 1, 0, 2, '"hmm, let\'s see"'],
['Connected to world app', 34, 1, 0, 3, '"hmm, what have we have here?"'],
['Connected to world app', 34, 1, 0, 4, '"oooh, very interesting"'],
['Connected to world app', 34, 1, 0, 5, '"hmmm"'],
['App name screen reactions', 35, 0, 0, 0, '"oooh, pick a good one!"'],
['App name screen reactions', 35, 0, 0, 1, '"hmm, which one oo-nye?"'],
['App name screen reactions', 35, 0, 0, 2, '"kah want that one!"'],
['App name screen reactions', 35, 0, 0, 3, '"ooh, name for kah?" (sing) "Oooh"'],
['App name screen reactions', 35, 0, 1, 0, '"huh, now that\'s a good name"'],
['App name screen reactions', 35, 0, 1, 1, '"hmm, kah like the sound of that"'],
['App name screen reactions', 35, 0, 1, 2, '"oooh, kah likey"'],
['App name screen reactions', 35, 0, 2, 0, 'shocked "best name evvaa" (sing)'],
['World App', 39, 0, 2, 0, '"Oooh, look"'],
['World App', 39, 0, 1, 3, '"ermagerd"'],
['World App', 39, 1, 1, 0, '"hmmm, let\'s see"'],
['World App', 39, 1, 1, 1, '"hmm, what have we have here?"'],
['World App', 39, 1, 1, 2, '"oooh, very interesting"'],
['World App', 39, 1, 1, 3, '"hmmm"'],
['World App', 39, 1, 9, 0, '"ee-tay, good job!"', 'praise'],
['World App', 39, 1, 9, 1, '"ee-tay, fantastico!"', 'praise'],
['World App', 39, 1, 9, 2, '"sweet mother of furb"'],
['World App', 39, 1, 9, 4, '"oooh, kah love it"'],
['World App', 39, 1, 9, 5, '"oooh, kah likey"'],
['World App', 39, 1, 9, 6, '"ooh, yeah, kah need this"'],
['World App', 39, 1, 9, 7, '"yay! ohhh ah uh ooo"'],
['World App', 39, 1, 9, 8, '"wow, we unstoppable"'],
['World App', 39, 1, 10, 0, '"oooh, ahh"'],
['World App', 39, 1, 10, 1, '"kah all like, whaaaat?!"'],
['World App', 39, 1, 10, 2, '"whoah"'],
['World App', 39, 1, 10, 3, '"mmmm"'],
['World App', 39, 1, 10, 4, '"ooh"'],
['World App', 39, 1, 10, 5, '"hey"'],
['World App', 39, 2, 4, 5, '"ermagerd"'],
['World App', 39, 3, 1, 4, '"ooooh, hello"'],
['World App', 39, 3, 1, 6, '"heeey"'],
['World App', 39, 3, 4, 0, '"let\'s name baby"'],
['World App', 39, 3, 5, 0, '"hmm, let\'s see."'],
['World App', 39, 3, 5, 1, '"hmm, what have we have here"'],
['World App', 39, 3, 5, 2, '"ooh, very interesting"'],
['World App', 39, 3, 5, 3, '"hmmm"'],
['World App', 39, 3, 6, 0, '"hmmm, special, really special"', 'praise'],
['World App', 39, 3, 8, 0, '"ooh, wow, just just wow"', 'praise'],
['World App', 39, 3, 8, 1, '"legendary!"', 'praise'],
['World App', 39, 4, 2, 0, '"get ready"'],
['World App', 39, 4, 6, 1, '"nice"'],
['World App', 39, 4, 6, 2, '"smooth move"'],
['World App', 39, 4, 6, 5, '"ee-tay fantastico"', 'praise'],
['World App', 39, 4, 7, 0, '"whoopsies"'],
['World App', 40, 0, 0, 0, '"Hey, Hey"'],
['World App', 40, 0, 0, 3, '"Oooh, hello"'],
['World App', 41, 0, 1, 0, '"ee-tay, good job!"', 'praise'],
['World App', 41, 0, 1, 2, '"Sweet mother of Furb!"'],
['World App', 41, 0, 1, 4, '"Oh, Kah love it"', 'praise'],
['World App', 41, 0, 1, 5, '"ooh, kay likey"', 'praise'],
['World App', 42, 0, 1, 4, '"oooh, new mission"'],
['World App', 42, 0, 3, 0, '"hey, help a furb out"'],
['World App', 42, 0, 4, 4, '"cmon, let\'s get started"'],
['World App', 42, 1, 0, 0, '"Weee diiid it!"', 'collab'],
['World App', 42, 1, 0, 1, '"ha, ha! Take that!"'],
['World App', 42, 1, 0, 2, '"hoho, we good, aww yeah"', 'collab'],
['World App', 42, 1, 0, 3, '"high five! wait, kah only have three"', 'collab'],
['World App', 42, 1, 0, 4, '"team furby for the win!"', 'collab'],
['World App', 43, 0, 0, 0, '"Hey, Hey"'],
['World App', 43, 0, 0, 2, '"Hey, Hey there, whoo"'],
['World App', 43, 0, 0, 5, '"Heeey"'],
['World App', 43, 0, 1, 0, '"Aaaaay, ada"'],
['World App', 43, 0, 2, 0, '"booboobooo, what\'s wrong"'],
['World App', 43, 0, 2, 1, '"ahhh, what\'s wrong"'],
['World App', 43, 0, 2, 2, '"oo-nye ok?"'],
['World App', 43, 0, 4, 0, '"let kah help"'],
['World App', 43, 0, 5, 0, '"hey! stop it"'],
['World App', 43, 0, 6, 0, '"what going on little dee-doh?"'],
['World App', 43, 0, 6, 1, '"so what oo-nye need?"'],
['World App', 43, 0, 7, 1, '"ahh, hold that thought"'],
['World App', 43, 0, 7, 2, '"go oon"'],
['World App', 43, 0, 7, 3, '"hmm"'],
['World App', 43, 0, 7, 4, '"oh, you"'],
['World App', 43, 0, 8, 0, '"honestly, yes"'],
['World App', 43, 0, 8, 1, '"mmm, hmm, totally"'],
['World App', 43, 0, 8, 2, '"ee-tay, a thousand times ee-tay"'],
['World App', 43, 0, 9, 0, '"ok, alright yes, let\'s doo this"'],
['World App', 43, 0, 9, 1, '"kah ready to go"'],
['World App', 43, 0, 9, 2, '"Let\'s get party started, uh"'],
['World App', 43, 0, 10, 0, '"bye bye for now"'],
['World App', 43, 0, 10, 2, '"see ya later, furbinator"'],
['World App', 43, 0, 10, 3, '"ok, hasta la bye-bye"'],
['World App', 44, 0, 0, 2, '"Oh, dis gonna be goood."'],
['World App', 55, 2, 1, 0, '"wrong way"'],
['World App', 55, 2, 1, 1, 'disapointed "aaaah"'],
['World App', 55, 2, 2, 0, '"Dat was Awwwwesome!"'],
['World App', 55, 2, 2, 1, '"Nice!"'],
['World App', 55, 2, 15, 0, 'stars in eyes "We did it!"'],
['World App', 55, 2, 16, 0, '"hey, over there"'],
['World App', 55, 2, 17, 0, 'ear point up, "Up"'],
['World App', 55, 2, 18, 0, '"down"'],
['World App', 55, 2, 19, 0, '"left"'],
['World App', 55, 2, 20, 0, '"right"'],
['World App', 55, 2, 21, 0, '"go back"'],
['World App', 55, 2, 22, 0, '"forwards"'],
['World App', 55, 2, 25, 0, '"again, again"'],
['How bout this one', 70, 0, 0, 0, 'How bout this one?'],
['Octave Notes', 71, 0, 0, 0, '"Do"'],
['Octave Notes', 71, 0, 0, 1, '"Re"'],
['Octave Notes', 71, 0, 0, 2, '"Mi"'],
['Octave Notes', 71, 0, 0, 3, '"Fa"'],
['Octave Notes', 71, 0, 0, 4, '"Sol"'],
['Octave Notes', 71, 0, 0, 5, '"La"'],
['Octave Notes', 71, 0, 0, 6, '"Ti"'],
['Octave Notes', 71, 0, 0, 7, '"Do"']
]
