module.exports = {
"oh ah oh oh ooooh": { params: [1, 0, 1, 0], name: "oh ah oh oh ooooh" },
"gaah (whispering) eugh!": { params: [1, 0, 1, 1], name: "gaah (whispering) eugh!" },
"you like? Is all natural!": { params: [1, 0, 1, 5], name: "you like? Is all natural!", emotions: "goofy" },
"doh, really?": { params: [1, 1, 0, 1], name: "doh, really?", emotions: "questioning,confused" },
"eeeeeehhhh": { params: [1, 1, 0, 2], name: "eeeeeehhhh" },
"wookie yawn": { params: [1, 1, 0, 3], name: "wookie yawn", emotions: "starwars,movies" },
"ooohmm.. Yay! (unexcited)": { params: [1, 1, 0, 4], name: "ooohmm.. Yay! (unexcited)", emotions: "unexcited" },
"ka-rumph": { params: [1, 1, 0, 5], name: "ka-rumph", emotions: "unexcited" },
"yawn besties?": { params: [1, 2, 0, 0], name: "yawn besties?", emotions: "friendly,sleepy" },
"yawn warm fuzzies": { params: [1, 2, 0, 1], name: "yawn warm fuzzies", emotions: "friendly,sleepy" },
"oooohhh, kah favorite!": { params: [1, 2, 0, 2], name: "oooohhh, kah favorite!", emotions: "content,loving" },
"ohohohoh… smoops": { params: [1, 2, 0, 3], name: "ohohohoh… smoops", emotions: "content,loving" },
"oooh, is this.. For ever??": { params: [1, 2, 0, 5], name: "oooh, is this.. For ever??", emotions: "content,loving,needy" },
"mmm… s s s s": { params: [1, 2, 0, 6], name: "mmm… s s s s" },
"do do, de de dey da do, da do": { params: [1, 2, 0, 7], name: "do do, de de dey da do, da do", emotions: "sleepy,singing" },
"aaah, kah on cloud nine, no, cloud ten": { params: [1, 2, 1, 0], name: "aaah, kah on cloud nine, no, cloud ten", emotions: "sleepy,content" },
"purr hmm. Kah dreaming?": { params: [1, 2, 1, 1], name: "purr hmm. Kah dreaming?", emotions: "sleepy,content,purr" },
"I love it!": { params: [1, 2, 1, 2], name: "I love it!", emotions: "praise,sleepy" },
"aaah fart": { params: [1, 2, 1, 4], name: "aaah fart", emotions: "sigh,fart" },
"sigh": { params: [1, 2, 1, 5], name: "sigh", emotions: "sigh" },
"oouuughhh": { params: [1, 3, 0, 1], name: "oouuughhh", emotions: "purr" },
"humming": { params: [1, 3, 0, 2], name: "humming" },
"frantic laughter": { params: [2, 0, 0, 0], name: "frantic laughter" },
"frantic laughter2": { params: [2, 0, 0, 1], name: "frantic laughter" },
"laughter, squeal": { params: [2, 0, 0, 2], name: "laughter, squeal" },
"wait, no! laughter": { params: [2, 0, 1, 0], name: "wait, no! laughter" },
"giggle, fart oh, excueeze kah!": { params: [2, 0, 1, 4], name: "giggle, fart oh, excueeze kah!" },
"he he he he he, hey, wait a minute": { params: [2, 1, 0, 5], name: "he he he he he, hey, wait a minute" },
"yawn hmm.. Puppies yip, giggle": { params: [2, 2, 0, 1], name: "yawn hmm.. Puppies yip, giggle" },
"giggle burger belly": { params: [2, 2, 1, 0], name: "giggle burger belly" },
"giggle, sigh": { params: [2, 2, 1, 1], name: "giggle, sigh" },
"gargle meh!": { params: [4, 1, 0, 4], name: "gargle meh!" },
"ugh! mumbles": { params: [4, 1, 0, 6], name: "ugh! mumbles" },
"sleep murmer cheese fries": { params: [4, 2, 0, 1], name: "sleep murmer cheese fries" },
"ee-tay, fantastico!": { params: [4, 3, 0, 8], name: "ee-tay, fantastico!", emotions: "praise" },
"oooh, oo-nye magic": { params: [4, 3, 0, 9], name: "oooh, oo-nye magic" },
"no, but seriously, kah love this!": { params: [5, 0, 1, 1], name: "no, but seriously, kah love this!", emotions: "praise" },
"hmm. Hug it out": { params: [5, 3, 0, 0], name: "hmm. Hug it out" },
"yaaaas": { params: [8, 0, 0, 0], name: "yaaaas" },
"what?!!": { params: [8, 0, 0, 7], name: "what?!!" },
"woah!": { params: [8, 0, 1, 6], name: "woah!" },
"shocked": { params: [8, 0, 1, 8], name: "shocked" },
"huh, this just got weird": { params: [8, 1, 0, 1], name: "huh, this just got weird" },
"uuuuuuuuuhhhh": { params: [8, 1, 0, 2], name: "uuuuuuuuuhhhh", emotions: "disapointment" },
"da no likey": { params: [8, 1, 0, 3], name: "da no likey", emotions: "disapointment" },
"awkward!": { params: [8, 1, 0, 4], name: "awkward!", emotions: "disapointment" },
"go on": { params: [8, 3, 0, 0], name: "go on" },
"oh yeah, no totally": { params: [8, 3, 0, 1], name: "oh yeah, no totally" },
"oooh": { params: [8, 3, 0, 2], name: "oooh" },
"daww": { params: [8, 3, 0, 4], name: "daww" },
"ah ohh!": { params: [8, 3, 0, 5], name: "ah ohh!" },
"hmmm": { params: [8, 3, 0, 6], name: "hmmm" },
"huh! Really!?": { params: [8, 3, 0, 7], name: "huh! Really!?" },
"oh oh, you!": { params: [8, 3, 0, 8], name: "oh oh, you!" },
"mm hmm, totally": { params: [8, 3, 0, 9], name: "mm hmm, totally" },
"oh, ee-tay, ee-day minds thing alike": { params: [8, 3, 0, 10], name: "oh, ee-tay, ee-day minds thing alike" },
"oooooohh, very interesting": { params: [8, 3, 0, 11], name: "oooooohh, very interesting" },
"dooo?? Gah boo!": { params: [8, 3, 0, 12], name: "dooo?? Gah boo!" },
"mm hm, kah no argue with that": { params: [8, 3, 0, 14], name: "mm hm, kah no argue with that" },
"pfth, oo kah tee, did kah tell you whisphers": { params: [8, 3, 0, 15], name: "pfth, oo kah tee, did kah tell you whisphers" },
"what we whisper about?": { params: [8, 3, 0, 16], name: "what we whisper about?" },
"yawn": { params: [25, 1, 0, 0], name: "yawn" },
"sigh": { params: [25, 1, 0, 1], name: "sigh" },
"hmmmmm": { params: [25, 1, 0, 2], name: "hmmmmm" },
"Buenos días": { params: [27, 2, 0, 0], name: "Buenos días" },
"Morning! Rise and shiney, ooh, shiney!": { params: [27, 2, 0, 1], name: "Morning! Rise and shiney, ooh, shiney!" },
"Morning! Early furb gets worm, nasty!": { params: [27, 2, 0, 2], name: "Morning! Early furb gets worm, nasty!" },
"power nap!": { params: [28, 0, 0, 2], name: "power nap!" },
"laugh no": { params: [30, 1, 1, 0], name: "laugh no" },
"uh oh": { params: [30, 1, 1, 3], name: "uh oh" },
"honestly, yes": { params: [30, 1, 1, 7], name: "honestly, yes" },
"mmm, maybe": { params: [30, 1, 1, 8], name: "mmm, maybe" },
"yaaaaas": { params: [30, 1, 1, 10], name: "yaaaaas" },
"what?": { params: [30, 1, 1, 11], name: "what?" },
"huh? No, wait, yes, wait, no?": { params: [30, 1, 1, 12], name: "huh? No, wait, yes, wait, no?" },
"indeed!": { params: [30, 1, 1, 20], name: "indeed!" },
"PUT TO SLEEP": { params: [30, 3, 0, 0], name: "PUT TO SLEEP" },
"love it!": { params: [32, 0, 0, 0], name: "love it!" },
"so in to this!": { params: [32, 0, 0, 1], name: "so in to this!" },
"hmm, not so sure": { params: [32, 0, 1, 0], name: "hmm, not so sure" },
"noo likey!": { params: [32, 0, 1, 1], name: "noo likey!" },
"caaan dig it": { params: [32, 0, 3, 0], name: "caaan dig it" },
"may-may oo-nye?": { params: [32, 0, 3, 1], name: "may-may oo-nye?" },
"need doctor coughs up lung": { params: [32, 0, 4, 0], name: "need doctor coughs up lung" },
"success! Kah has it": { params: [34, 0, 0, 2], name: "success! Kah has it" },
"yes! The day is ours (weird accent)": { params: [34, 0, 0, 3], name: "yes! The day is ours (weird accent)" },
"oooh, oo-nye magic": { params: [34, 0, 0, 4], name: "oooh, oo-nye magic" },
"dude, dee-doh, yes, very yes": { params: [34, 0, 0, 5], name: "dude, dee-doh, yes, very yes" },
"ooh silly laugh": { params: [34, 0, 0, 6], name: "ooh silly laugh" },
"neeeeeeehe": { params: [34, 0, 0, 7], name: "neeeeeeehe" },
"oh ah oh oh oh": { params: [34, 0, 0, 8], name: "oh ah oh oh oh" },
"heh, menus, am I right?": { params: [34, 1, 0, 0], name: "heh, menus, am I right?" },
"hmm, let's see": { params: [34, 1, 0, 2], name: "hmm, let's see" },
"hmm, what have we have here?": { params: [34, 1, 0, 3], name: "hmm, what have we have here?" },
"oooh, very interesting": { params: [34, 1, 0, 4], name: "oooh, very interesting" },
"hmmm": { params: [34, 1, 0, 5], name: "hmmm" },
"oooh, pick a good one!": { params: [35, 0, 0, 0], name: "oooh, pick a good one!" },
"hmm, which one oo-nye?": { params: [35, 0, 0, 1], name: "hmm, which one oo-nye?" },
"kah want that one!": { params: [35, 0, 0, 2], name: "kah want that one!" },
"ooh, name for kah? (sing) Oooh": { params: [35, 0, 0, 3], name: "ooh, name for kah? (sing) Oooh" },
"huh, now that's a good name": { params: [35, 0, 1, 0], name: "huh, now that's a good name" },
"hmm, kah like the sound of that": { params: [35, 0, 1, 1], name: "hmm, kah like the sound of that" },
"oooh, kah likey": { params: [35, 0, 1, 2], name: "oooh, kah likey" },
"shocked best name evvaa (sing)": { params: [35, 0, 2, 0], name: "shocked best name evvaa (sing)" },
"Oooh, look": { params: [39, 0, 2, 0], name: "Oooh, look" },
"ermagerd": { params: [39, 0, 1, 3], name: "ermagerd" },
"hmmm, let's see": { params: [39, 1, 1, 0], name: "hmmm, let's see" },
"hmm, what have we have here?": { params: [39, 1, 1, 1], name: "hmm, what have we have here?" },
"oooh, very interesting": { params: [39, 1, 1, 2], name: "oooh, very interesting" },
"hmmm": { params: [39, 1, 1, 3], name: "hmmm" },
"ee-tay, good job!": { params: [39, 1, 9, 0], name: "ee-tay, good job!", emotions: "praise" },
"ee-tay, fantastico!": { params: [39, 1, 9, 1], name: "ee-tay, fantastico!", emotions: "praise" },
"sweet mother of furb": { params: [39, 1, 9, 2], name: "sweet mother of furb" },
"oooh, kah love it": { params: [39, 1, 9, 4], name: "oooh, kah love it" },
"oooh, kah likey": { params: [39, 1, 9, 5], name: "oooh, kah likey" },
"ooh, yeah, kah need this": { params: [39, 1, 9, 6], name: "ooh, yeah, kah need this" },
"yay! ohhh ah uh ooo": { params: [39, 1, 9, 7], name: "yay! ohhh ah uh ooo" },
"wow, we unstoppable": { params: [39, 1, 9, 8], name: "wow, we unstoppable" },
"oooh, ahh": { params: [39, 1, 10, 0], name: "oooh, ahh" },
"kah all like, whaaaat?!": { params: [39, 1, 10, 1], name: "kah all like, whaaaat?!" },
"whoah": { params: [39, 1, 10, 2], name: "whoah" },
"mmmm": { params: [39, 1, 10, 3], name: "mmmm" },
"ooh": { params: [39, 1, 10, 4], name: "ooh" },
"hey": { params: [39, 1, 10, 5], name: "hey" },
"ermagerd": { params: [39, 2, 4, 5], name: "ermagerd" },
"ooooh, hello": { params: [39, 3, 1, 4], name: "ooooh, hello" },
"heeey": { params: [39, 3, 1, 6], name: "heeey" },
"let's name baby": { params: [39, 3, 4, 0], name: "let's name baby" },
"hmm, let's see.": { params: [39, 3, 5, 0], name: "hmm, let's see." },
"hmm, what have we have here": { params: [39, 3, 5, 1], name: "hmm, what have we have here" },
"ooh, very interesting": { params: [39, 3, 5, 2], name: "ooh, very interesting" },
"hmmm": { params: [39, 3, 5, 3], name: "hmmm" },
"hmmm, special, really special": { params: [39, 3, 6, 0], name: "hmmm, special, really special", emotions: "praise" },
"ooh, wow, just just wow": { params: [39, 3, 8, 0], name: "ooh, wow, just just wow", emotions: "praise" },
"legendary!": { params: [39, 3, 8, 1], name: "legendary!", emotions: "praise" },
"get ready": { params: [39, 4, 2, 0], name: "get ready" },
"nice": { params: [39, 4, 6, 1], name: "nice" },
"smooth move": { params: [39, 4, 6, 2], name: "smooth move" },
"ee-tay fantastico": { params: [39, 4, 6, 5], name: "ee-tay fantastico", emotions: "praise" },
"whoopsies": { params: [39, 4, 7, 0], name: "whoopsies" },
"Hey, Hey": { params: [40, 0, 0, 0], name: "Hey, Hey" },
"Oooh, hello": { params: [40, 0, 0, 3], name: "Oooh, hello" },
"ee-tay, good job!": { params: [41, 0, 1, 0], name: "ee-tay, good job!", emotions: "praise" },
"Sweet mother of Furb!": { params: [41, 0, 1, 2], name: "Sweet mother of Furb!" },
"Oh, Kah love it": { params: [41, 0, 1, 4], name: "Oh, Kah love it", emotions: "praise" },
"ooh, kay likey": { params: [41, 0, 1, 5], name: "ooh, kay likey", emotions: "praise" },
"oooh, new mission": { params: [42, 0, 1, 4], name: "oooh, new mission" },
"hey, help a furb out": { params: [42, 0, 3, 0], name: "hey, help a furb out" },
"cmon, let's get started": { params: [42, 0, 4, 4], name: "cmon, let's get started" },
"Weee diiid it!": { params: [42, 1, 0, 0], name: "Weee diiid it!", emotions: "collab" },
"ha, ha! Take that!": { params: [42, 1, 0, 1], name: "ha, ha! Take that!" },
"hoho, we good, aww yeah": { params: [42, 1, 0, 2], name: "hoho, we good, aww yeah", emotions: "collab" },
"high five! wait, kah only have three": { params: [42, 1, 0, 3], name: "high five! wait, kah only have three", emotions: "collab,praise" },
"team furby for the win!": { params: [42, 1, 0, 4], name: "team furby for the win!", emotions: "collab" },
"Hey, Hey": { params: [43, 0, 0, 0], name: "Hey, Hey" },
"Hey, Hey there, whoo": { params: [43, 0, 0, 2], name: "Hey, Hey there, whoo" },
"Heeey": { params: [43, 0, 0, 5], name: "Heeey" },
"Aaaaay, ada": { params: [43, 0, 1, 0], name: "Aaaaay, ada" },
"booboobooo, what's wrong": { params: [43, 0, 2, 0], name: "booboobooo, what's wrong" },
"ahhh, what's wrong": { params: [43, 0, 2, 1], name: "ahhh, what's wrong" },
"oo-nye ok?": { params: [43, 0, 2, 2], name: "oo-nye ok?" },
"let kah help": { params: [43, 0, 4, 0], name: "let kah help" },
"hey! stop it": { params: [43, 0, 5, 0], name: "hey! stop it" },
"what going on little dee-doh?": { params: [43, 0, 6, 0], name: "what going on little dee-doh?" },
"so what oo-nye need?": { params: [43, 0, 6, 1], name: "so what oo-nye need?" },
"ahh, hold that thought": { params: [43, 0, 7, 1], name: "ahh, hold that thought" },
"go oon": { params: [43, 0, 7, 2], name: "go oon" },
"hmm": { params: [43, 0, 7, 3], name: "hmm" },
"oh, you": { params: [43, 0, 7, 4], name: "oh, you" },
"honestly, yes": { params: [43, 0, 8, 0], name: "honestly, yes" },
"mmm, hmm, totally": { params: [43, 0, 8, 1], name: "mmm, hmm, totally" },
"ee-tay, a thousand times ee-tay": { params: [43, 0, 8, 2], name: "ee-tay, a thousand times ee-tay" },
"ok, alright yes, let's doo this": { params: [43, 0, 9, 0], name: "ok, alright yes, let's doo this", emotions: "hello" },
"kah ready to go": { params: [43, 0, 9, 1], name: "kah ready to go", emotions: "hello" },
"Let's get party started, uh": { params: [43, 0, 9, 2], name: "Let's get party started, uh", emotions: "hello" },
"bye bye for now": { params: [43, 0, 10, 0], name: "bye bye for now", emotions: "goodbye" },
"see ya later, furbinator": { params: [43, 0, 10, 2], name: "see ya later, furbinator", emotions: "goodbye" },
"ok, hasta la bye-bye": { params: [43, 0, 10, 3], name: "ok, hasta la bye-bye", emotions: "goodbye" },
"Oh, dis gonna be goood.": { params: [44, 0, 0, 2], name: "Oh, dis gonna be goood.", emotions: "excitement" },
"wrong way": { params: [55, 2, 1, 0], name: "wrong way", emotions: "disapointment,directing" },
"disapointed aaaah": { params: [55, 2, 1, 1], name: "disapointed aaaah", emotions: "disapointment" },
"Dat was Awwwwesome!": { params: [55, 2, 2, 0], name: "Dat was Awwwwesome!", emotions: "praise,excitement" },
"Nice!": { params: [55, 2, 2, 1], name: "Nice!", emotions: "praise" },
"stars in eyes We did it!": { params: [55, 2, 15, 0], name: "stars in eyes We did it!", emotions: "praise" },
"hey, over there": { params: [55, 2, 16, 0], name: "hey, over there", emotions: "directing" },
"ear point up, Up": { params: [55, 2, 17, 0], name: "ear point up, Up", emotions: "directing" },
"down": { params: [55, 2, 18, 0], name: "down", emotions: "directing" },
"left": { params: [55, 2, 19, 0], name: "left", emotions: "directing" },
"right": { params: [55, 2, 20, 0], name: "right", emotions: "directing" },
"go back": { params: [55, 2, 21, 0], name: "go back", emotions: "directing" },
"forwards": { params: [55, 2, 22, 0], name: "forwards", emotions: "directing" },
"again, again": { params: [55, 2, 25, 0], name: "again, again", emotions: "collab" },
"How bout this one?": { params: [70, 0, 0, 0], name: "How bout this one?", emotions: "collab,question" },
"Do": { params: [71, 0, 0, 0], name: "Do" },
"Re": { params: [71, 0, 0, 1], name: "Re" },
"Mi": { params: [71, 0, 0, 2], name: "Mi" },
"Fa": { params: [71, 0, 0, 3], name: "Fa" },
"Sol": { params: [71, 0, 0, 4], name: "Sol" },
"La": { params: [71, 0, 0, 5], name: "La" },
"Ti": { params: [71, 0, 0, 6], name: "Ti" },
"Do": { params: [71, 0, 0, 7], name: "Do" }
}
