module.exports = {
"oh ah oh oh ooooh": { params: [1, 0, 1, 0], name: "oh ah oh oh ooooh", emotions: "goofy" },
"gaah (whispering) eugh!": { params: [1, 0, 1, 1], name: "gaah (whispering) eugh!", emotions: "goofy" },
"you like? Is all natural!": { params: [1, 0, 1, 5], name: "you like? Is all natural!", emotions: "goofy,questioning" },
"doh, really?": { params: [1, 1, 0, 1], name: "doh, really?", emotions: "questioning,confused,disappointment" },
"eeeeeehhhh": { params: [1, 1, 0, 2], name: "eeeeeehhhh" },
"wookie yawn": { params: [1, 1, 0, 3], name: "wookie yawn", emotions: "starwars,movies,goofy" },
"ooohmm.. Yay! (unexcited)": { params: [1, 1, 0, 4], name: "ooohmm.. Yay! (unexcited)", emotions: "unexcited" },
"ka-rumph": { params: [1, 1, 0, 5], name: "ka-rumph", emotions: "disappointment" },
"yawn besties?": { params: [1, 2, 0, 0], name: "yawn besties?", emotions: "friendly,sleepy,questioning" },
"yawn warm fuzzies": { params: [1, 2, 0, 1], name: "yawn warm fuzzies", emotions: "friendly,sleepy" },
"oooohhh, kah favorite!": { params: [1, 2, 0, 2], name: "oooohhh, kah favorite!", emotions: "content,loving" },
"ohohohoh… smoops": { params: [1, 2, 0, 3], name: "ohohohoh… smoops", emotions: "content,loving" },
"oooh, is this.. For ever??": { params: [1, 2, 0, 5], name: "oooh, is this.. For ever??", emotions: "content,loving,needy,questioning" },
"mmm… s s s s": { params: [1, 2, 0, 6], name: "mmm… s s s s" },
"do do, de de dey da do, da do": { params: [1, 2, 0, 7], name: "do do, de de dey da do, da do", emotions: "sleepy,singing" },
"aaah, kah on cloud nine, no, cloud ten": { params: [1, 2, 1, 0], name: "aaah, kah on cloud nine, no, cloud ten", emotions: "sleepy,content" },
"purr hmm. Kah dreaming?": { params: [1, 2, 1, 1], name: "purr hmm. Kah dreaming?", emotions: "sleepy,content,purr" },
"I love it!": { params: [1, 2, 1, 2], name: "I love it!", emotions: "praise" },
"aaah fart": { params: [1, 2, 1, 4], name: "aaah fart", emotions: "sigh,fart" },
"sigh": { params: [1, 2, 1, 5], name: "sigh", emotions: "sigh,disappointment" },
"oouuughhh": { params: [1, 3, 0, 1], name: "oouuughhh", emotions: "purr" },
"humming": { params: [1, 3, 0, 2], name: "humming" },
"frantic laughter": { params: [2, 0, 0, 0], name: "frantic laughter", emotions: "laughter" },
"frantic laughter2": { params: [2, 0, 0, 1], name: "frantic laughter", emotions: "laughter" },
"laughter, squeal": { params: [2, 0, 0, 2], name: "laughter, squeal", emotions: "laughter" },
"wait, no! laughter": { params: [2, 0, 1, 0], name: "wait, no! laughter", emotions: "laughter" },
"giggle, fart oh, excueeze kah!": { params: [2, 0, 1, 4], name: "giggle, fart oh, excueeze kah!", emotions:"humor" },
"he he he he he, hey, wait a minute": { params: [2, 1, 0, 5], name: "he he he he he, hey, wait a minute", emotions: "smalltalk" },
"yawn hmm.. Puppies yip, giggle": { params: [2, 2, 0, 1], name: "yawn hmm.. Puppies yip, giggle", emotions: "giggle,laughter" },
"giggle burger belly": { params: [2, 2, 1, 0], name: "giggle burger belly", emotions: "giggle,laughter" },
"giggle, sigh": { params: [2, 2, 1, 1], name: "giggle, sigh", emotions: "giggle,laughter" },
"gargle meh!": { params: [4, 1, 0, 4], name: "gargle meh!", emotions: "disappointment" },
"ugh! mumbles": { params: [4, 1, 0, 6], name: "ugh! mumbles", emotions: "disappointment" },
"sleep murmer cheese fries": { params: [4, 2, 0, 1], name: "sleep murmer cheese fries", emotions: "sleepy" },
"ee-tay, fantastico!": { params: [4, 3, 0, 8], name: "ee-tay, fantastico!", emotions: "praise,excitement" },
"oooh, oo-nye magic": { params: [4, 3, 0, 9], name: "oooh, oo-nye magic", emotions: "magic" },
"no, but seriously, kah love this!": { params: [5, 0, 1, 1], name: "no, but seriously, kah love this!", emotions: "praise" },
"hmm. Hug it out": { params: [5, 3, 0, 0], name: "hmm. Hug it out" },
"yaaaas": { params: [8, 0, 0, 0], name: "yaaaas", emotions: "yes,praise" },
"what?!!": { params: [8, 0, 0, 7], name: "what?!!", emotions: "questioning" },
"woah!": { params: [8, 0, 1, 6], name: "woah!", emotions: "excitement" },
"shocked": { params: [8, 0, 1, 8], name: "shocked", emotions: "shocked" },
"huh, this just got weird": { params: [8, 1, 0, 1], name: "huh, this just got weird", emotions: "weird,awkward" },
"uuuuuuuuuhhhh": { params: [8, 1, 0, 2], name: "uuuuuuuuuhhhh", emotions: "disappointment" },
"da no likey": { params: [8, 1, 0, 3], name: "da no likey", emotions: "disappointment" },
"awkward!": { params: [8, 1, 0, 4], name: "awkward!", emotions: "disappointment" },
"go on": { params: [8, 3, 0, 0], name: "go on", emotions: "collab" },
"oh yeah, no totally": { params: [8, 3, 0, 1], name: "oh yeah, no totally", emotions: "collab,smalltalk" },
"oooh": { params: [8, 3, 0, 2], name: "oooh", emotions: "smalltalk,collab" },
"daww": { params: [8, 3, 0, 4], name: "daww", emotions: "smalltalk,collab" },
"ah ohh!": { params: [8, 3, 0, 5], name: "ah ohh!", emotions: "smalltalk" },
"hmmm4": { params: [8, 3, 0, 6], name: "hmmm", emotions: "smalltalk" },
"huh! Really!?": { params: [8, 3, 0, 7], name: "huh! Really!?", emotions: "questioning" },
"oh oh, you!": { params: [8, 3, 0, 8], name: "oh oh, you!", emotions: "excitement,praise" },
"mm hmm, totally": { params: [8, 3, 0, 9], name: "mm hmm, totally", emotions: "excitement,praise" },
"oh, ee-tay, ee-day minds thing alike": { params: [8, 3, 0, 10], name: "oh, ee-tay, ee-day minds thing alike", emotions: "praise" },
"oooooohh, very interesting": { params: [8, 3, 0, 11], name: "oooooohh, very interesting", emotions: "smalltalk,collab" },
"dooo?? Gah boo!": { params: [8, 3, 0, 12], name: "dooo?? Gah boo!", emotions: "questioning" },
"mm hm, kah no argue with that": { params: [8, 3, 0, 14], name: "mm hm, kah no argue with that", emotions: "collab" },
"pfth, oo kah tee, did kah tell you whisphers": { params: [8, 3, 0, 15], name: "pfth, oo kah tee, did kah tell you whisphers" },
"what we whisper about?": { params: [8, 3, 0, 16], name: "what we whisper about?", emotions: "questioning" },
"yawn": { params: [25, 1, 0, 0], name: "yawn", emotions: "sleepy,collab" },
"sigh": { params: [25, 1, 0, 1], name: "sigh", emotions: "sleepy" },
"hmmmmm": { params: [25, 1, 0, 2], name: "hmmmmm", emotions: "unsure" },
"Buenos días": { params: [27, 2, 0, 0], name: "Buenos días", emotions: "hello" },
"Morning! Rise and shiney, ooh, shiney!": { params: [27, 2, 0, 1], name: "Morning! Rise and shiney, ooh, shiney!", emotions: "hello" },
"Morning! Early furb gets worm, nasty!": { params: [27, 2, 0, 2], name: "Morning! Early furb gets worm, nasty!", emotions: "hello" },
"power nap!": { params: [28, 0, 0, 2], name: "power nap!", emotions: "sleepy" },
"laugh no": { params: [30, 1, 1, 0], name: "laugh no", emotions: "no" },
"uh oh": { params: [30, 1, 1, 3], name: "uh oh", emotions: "disappointment" },
"honestly, yes": { params: [30, 1, 1, 7], name: "honestly, yes", emotions: "yes" },
"mmm, maybe": { params: [30, 1, 1, 8], name: "mmm, maybe", emotions: "unsure" },
"yaaaaas": { params: [30, 1, 1, 10], name: "yaaaaas", emotions: "praise,excitement" },
"what?": { params: [30, 1, 1, 11], name: "what?", emotions: "questioning,collab" },
"huh? No, wait, yes, wait, no?": { params: [30, 1, 1, 12], name: "huh? No, wait, yes, wait, no?", emotions: "unsure,collab" },
"indeed!": { params: [30, 1, 1, 20], name: "indeed!", emotions:"praise" },
"PUT TO SLEEP": { params: [30, 3, 0, 0], name: "PUT TO SLEEP" },
"love it!": { params: [32, 0, 0, 0], name: "love it!", emotions: "praise" },
"so in to this!": { params: [32, 0, 0, 1], name: "so in to this!", emotions: "excitement" },
"hmm, not so sure": { params: [32, 0, 1, 0], name: "hmm, not so sure", emotions: "unsure,thinking,disappointment" },
"noo likey!": { params: [32, 0, 1, 1], name: "noo likey!", emotions: "disappointment" },
"caaan dig it": { params: [32, 0, 3, 0], name: "caaan dig it", emotions: "excitement" },
"may-may oo-nye?": { params: [32, 0, 3, 1], name: "may-may oo-nye?", emotions: "questioning" },
"need doctor coughs up lung": { params: [32, 0, 4, 0], name: "need doctor coughs up lung", emotions: "sick" },
"success! Kah has it": { params: [34, 0, 0, 2], name: "success! Kah has it", emotions: "praise" },
"yes! The day is ours (weird accent)": { params: [34, 0, 0, 3], name: "yes! The day is ours (weird accent)", emotions: "praise" },
"oooh, oo-nye magic2": { params: [34, 0, 0, 4], name: "oooh, oo-nye magic", emotions: "magic" },
"dude, dee-doh, yes, very yes": { params: [34, 0, 0, 5], name: "dude, dee-doh, yes, very yes", emotions: "praise" },
"ooh silly laugh": { params: [34, 0, 0, 6], name: "ooh silly laugh", emotions: "laughing,praise" },
"neeeeeeehe": { params: [34, 0, 0, 7], name: "neeeeeeehe", emotions: "excitement" },
"oh ah oh oh oh": { params: [34, 0, 0, 8], name: "oh ah oh oh oh", emotions: "praise" },
"heh, menus, am I right?": { params: [34, 1, 0, 0], name: "heh, menus, am I right?", emotions: "questioning" },
"hmm, let's see": { params: [34, 1, 0, 2], name: "hmm, let's see", emotions: "thinking,collab" },
"hmm, what have we have here?": { params: [34, 1, 0, 3], name: "hmm, what have we have here?", emotions: "thinking,collab" },
"oooh, very interesting": { params: [34, 1, 0, 4], name: "oooh, very interesting", emotions: "thinking" },
"hmmm5": { params: [34, 1, 0, 5], name: "hmmm" },
"oooh, pick a good one!": { params: [35, 0, 0, 0], name: "oooh, pick a good one!" },
"hmm, which one oo-nye?": { params: [35, 0, 0, 1], name: "hmm, which one oo-nye?", emotions: "questioning" },
"kah want that one!": { params: [35, 0, 0, 2], name: "kah want that one!" },
"ooh, name for kah? (sing) Oooh": { params: [35, 0, 0, 3], name: "ooh, name for kah? (sing) Oooh" },
"huh, now that's a good name": { params: [35, 0, 1, 0], name: "huh, now that's a good name" },
"hmm, kah like the sound of that": { params: [35, 0, 1, 1], name: "hmm, kah like the sound of that", emotions: "excitement" },
"oooh, kah likey": { params: [35, 0, 1, 2], name: "oooh, kah likey", emotions: "excitement" },
"shocked best name evvaa (sing)": { params: [35, 0, 2, 0], name: "shocked best name evvaa (sing)" },
"Oooh, look": { params: [39, 0, 2, 0], name: "Oooh, look" },
"ermagerd": { params: [39, 0, 1, 3], name: "ermagerd", emotions: "disappointment" },
"hmmm, let's see": { params: [39, 1, 1, 0], name: "hmmm, let's see", emotions: "thinking,collab" },
"hmm, what have we have here?": { params: [39, 1, 1, 1], name: "hmm, what have we have here?", emotions: "thinking" },
"oooh, very interesting": { params: [39, 1, 1, 2], name: "oooh, very interesting", emotions: "thinking" },
"hmmm2": { params: [39, 1, 1, 3], name: "hmmm", emotions: "smalltalk" },
"ee-tay, good job!": { params: [39, 1, 9, 0], name: "ee-tay, good job!", emotions: "praise" },
"ee-tay, fantastico2!": { params: [39, 1, 9, 1], name: "ee-tay, fantastico!", emotions: "praise" },
"sweet mother of furb": { params: [39, 1, 9, 2], name: "sweet mother of furb", emotions: "excitement,praise" },
"oooh, kah love it": { params: [39, 1, 9, 4], name: "oooh, kah love it", emotions: "praise" },
"oooh, kah likey2": { params: [39, 1, 9, 5], name: "oooh, kah likey", emotions: "praise" },
"ooh, yeah, kah need this": { params: [39, 1, 9, 6], name: "ooh, yeah, kah need this" },
"yay! ohhh ah uh ooo": { params: [39, 1, 9, 7], name: "yay! ohhh ah uh ooo", emotions: "praise" },
"wow, we unstoppable": { params: [39, 1, 9, 8], name: "wow, we unstoppable", emotions: "praise,excitement" },
"oooh, ahh": { params: [39, 1, 10, 0], name: "oooh, ahh", emotions: "smalltalk,praise" },
"kah all like, whaaaat?!": { params: [39, 1, 10, 1], name: "kah all like, whaaaat?!", emotions: "excitement,collab" },
"whoah": { params: [39, 1, 10, 2], name: "whoah", emotions: "smalltak" },
"mmmm": { params: [39, 1, 10, 3], name: "mmmm", emotions: "smalltalk,praise" },
"ooh": { params: [39, 1, 10, 4], name: "ooh", emotions: "smalltalk,praise" },
"hey": { params: [39, 1, 10, 5], name: "hey", emotions: "smalltalk,praise" },
"ermagerd2": { params: [39, 2, 4, 5], name: "ermagerd" },
"ooooh, hello": { params: [39, 3, 1, 4], name: "ooooh, hello", emotions: "hello" },
"heeey": { params: [39, 3, 1, 6], name: "heeey", emotions: "hello" },
"let's name baby": { params: [39, 3, 4, 0], name: "let's name baby" },
"hmm, let's see.": { params: [39, 3, 5, 0], name: "hmm, let's see.", emotions: "smalltalk,thinking,collab" },
"hmm, what have we have here": { params: [39, 3, 5, 1], name: "hmm, what have we have here", emotions: "smalltalk,thinking" },
"ooh, very interesting": { params: [39, 3, 5, 2], name: "ooh, very interesting", emotions: "smalltalk,thinking,collab" },
"hmmm3": { params: [39, 3, 5, 3], name: "hmmm", emotions: "smalltalk" },
"hmmm, special, really special": { params: [39, 3, 6, 0], name: "hmmm, special, really special" },
"ooh, wow, just just wow": { params: [39, 3, 8, 0], name: "ooh, wow, just just wow", emotions: "praise" },
"legendary!": { params: [39, 3, 8, 1], name: "legendary!", emotions: "praise" },
"get ready": { params: [39, 4, 2, 0], name: "get ready", emotions: "beginning" },
"nice": { params: [39, 4, 6, 1], name: "nice", emotions: "praise" },
"smooth move": { params: [39, 4, 6, 2], name: "smooth move", emotions: "praise" },
"ee-tay fantastico": { params: [39, 4, 6, 5], name: "ee-tay fantastico", emotions: "praise" },
"whoopsies": { params: [39, 4, 7, 0], name: "whoopsies", emotions: "disappointment" },
"Hey, Hey": { params: [40, 0, 0, 0], name: "Hey, Hey", emotions: "hello" },
"Oooh, hello": { params: [40, 0, 0, 3], name: "Oooh, hello", emotions: "hello" },
"ee-tay, good job!": { params: [41, 0, 1, 0], name: "ee-tay, good job!", emotions: "praise" },
"Sweet mother of Furb!": { params: [41, 0, 1, 2], name: "Sweet mother of Furb!", emotions: "praise,excitement" },
"Oh, Kah love it": { params: [41, 0, 1, 4], name: "Oh, Kah love it", emotions: "praise" },
"ooh, kay likey": { params: [41, 0, 1, 5], name: "ooh, kay likey", emotions: "praise" },
"oooh, new mission": { params: [42, 0, 1, 4], name: "oooh, new mission", emotions:"beginning" },
"hey, help a furb out": { params: [42, 0, 3, 0], name: "hey, help a furb out" },
"cmon, let's get started": { params: [42, 0, 4, 4], name: "cmon, let's get started", emotions:"beginning,hello" },
"Weee diiid it!": { params: [42, 1, 0, 0], name: "Weee diiid it!", emotions: "collab,excitement" },
"ha, ha! Take that!": { params: [42, 1, 0, 1], name: "ha, ha! Take that!", emotions: "excitement,praise" },
"hoho, we good, aww yeah": { params: [42, 1, 0, 2], name: "hoho, we good, aww yeah", emotions: "collab,praise" },
"high five! wait, kah only have three": { params: [42, 1, 0, 3], name: "high five! wait, kah only have three", emotions: "collab,praise" },
"team furby for the win!": { params: [42, 1, 0, 4], name: "team furby for the win!", emotions: "collab" },
"Hey, Hey2": { params: [43, 0, 0, 0], name: "Hey, Hey", emotions:"attention,hello" },
"Hey, Hey there, whoo": { params: [43, 0, 0, 2], name: "Hey, Hey there, whoo", emotions:"attention" },
"Heeey": { params: [43, 0, 0, 5], name: "Heeey", emotions:"attention" },
"Aaaaay, ada": { params: [43, 0, 1, 0], name: "Aaaaay, ada", emotions:"attention" },
"booboobooo, what's wrong": { params: [43, 0, 2, 0], name: "booboobooo, what's wrong", emotions:"questioning,concern" },
"ahhh, what's wrong": { params: [43, 0, 2, 1], name: "ahhh, what's wrong", emotions:"questioning,concern" },
"oo-nye ok?": { params: [43, 0, 2, 2], name: "oo-nye ok?", emotions:"questioning,concern" },
"let kah help": { params: [43, 0, 4, 0], name: "let kah help", emotions:"helpful,collab" },
"hey! stop it": { params: [43, 0, 5, 0], name: "hey! stop it", emotions:"frustrated" },
"what going on little dee-doh?": { params: [43, 0, 6, 0], name: "what going on little dee-doh?", emotions:"questioning" },
"so what oo-nye need?": { params: [43, 0, 6, 1], name: "so what oo-nye need?", emotions:"questioning,collab" },
"ahh, hold that thought": { params: [43, 0, 7, 1], name: "ahh, hold that thought", emotions: "collab" },
"go oon": { params: [43, 0, 7, 2], name: "go oon", emotions: "collab" },
"hmm": { params: [43, 0, 7, 3], name: "hmm" },
"oh, you": { params: [43, 0, 7, 4], name: "oh, you", emotions: "smalltalk" },
"honestly, yes": { params: [43, 0, 8, 0], name: "honestly, yes", emotions: "collab" },
"mmm, hmm, totally": { params: [43, 0, 8, 1], name: "mmm, hmm, totally", emotions: "collab" },
"ee-tay, a thousand times ee-tay": { params: [43, 0, 8, 2], name: "ee-tay, a thousand times ee-tay", emotions:"collab" },
"ok, alright yes, let's doo this": { params: [43, 0, 9, 0], name: "ok, alright yes, let's doo this", emotions: "hello,beginning" },
"kah ready to go": { params: [43, 0, 9, 1], name: "kah ready to go", emotions: "hello,beginning" },
"Let's get party started, uh": { params: [43, 0, 9, 2], name: "Let's get party started, uh", emotions: "hello,beginning" },
"bye bye for now": { params: [43, 0, 10, 0], name: "bye bye for now", emotions: "goodbye" },
"see ya later, furbinator": { params: [43, 0, 10, 2], name: "see ya later, furbinator", emotions: "goodbye" },
"ok, hasta la bye-bye": { params: [43, 0, 10, 3], name: "ok, hasta la bye-bye", emotions: "goodbye" },
"Oh, dis gonna be goood.": { params: [44, 0, 0, 2], name: "Oh, dis gonna be goood.", emotions: "excitement" },
"wrong way": { params: [55, 2, 1, 0], name: "wrong way", emotions: "disappointment,directing" },
"disappointed aaaah": { params: [55, 2, 1, 1], name: "disappointed aaaah", emotions: "disappointment" },
"Dat was Awwwwesome!": { params: [55, 2, 2, 0], name: "Dat was Awwwwesome!", emotions: "praise,excitement" },
"Nice!": { params: [55, 2, 2, 1], name: "Nice!", emotions: "praise" },
"stars in eyes We did it!": { params: [55, 2, 15, 0], name: "stars in eyes We did it!", emotions: "praise" },
"hey, over there": { params: [55, 2, 16, 0], name: "hey, over there", emotions: "directing" },
"ear point up, Up": { params: [55, 2, 17, 0], name: "ear point up, Up", emotions: "directing" },
"down": { params: [55, 2, 18, 0], name: "down", emotions: "directing" },
"left": { params: [55, 2, 19, 0], name: "left", emotions: "directing" },
"right": { params: [55, 2, 20, 0], name: "right", emotions: "directing" },
"go back": { params: [55, 2, 21, 0], name: "go back", emotions: "directing" },
"forwards": { params: [55, 2, 22, 0], name: "forwards", emotions: "directing" },
"again, again": { params: [55, 2, 25, 0], name: "again, again", emotions: "collab" },
"How bout this one?": { params: [70, 0, 0, 0], name: "How bout this one?", emotions: "collab,question" },
"Do": { params: [71, 0, 0, 0], name: "Do" },
"Re": { params: [71, 0, 0, 1], name: "Re" },
"Mi": { params: [71, 0, 0, 2], name: "Mi" },
"Fa": { params: [71, 0, 0, 3], name: "Fa" },
"Sol": { params: [71, 0, 0, 4], name: "Sol" },
"La": { params: [71, 0, 0, 5], name: "La" },
"Ti": { params: [71, 0, 0, 6], name: "Ti" },
"Do2": { params: [71, 0, 0, 7], name: "Do" }
}
